import os
import pg8000
import pandas as pd
from dotenv import load_dotenv
import ssl

load_dotenv()

# Debug: Print configuration (without password)
print("🔍 Checking configuration...")
print(f"   DB_USER: {os.getenv('DB_USER')}")
print(f"   DB_HOST: {os.getenv('DB_HOST')}")
print(f"   DB_PORT: {os.getenv('DB_PORT', 5432)}")
print(f"   DB_NAME: {os.getenv('DB_NAME')}")
print(f"   DB_PASSWORD: {'*' * len(os.getenv('DB_PASSWORD', '')) if os.getenv('DB_PASSWORD') else 'NOT SET'}")

# Create SSL context for Neon
ssl_context = ssl.create_default_context()
ssl_context.check_hostname = False
ssl_context.verify_mode = ssl.CERT_NONE

DB_CONFIG = {
    "user": os.getenv("DB_USER"),
    "password": os.getenv("DB_PASSWORD"),
    "host": os.getenv("DB_HOST"),
    "port": int(os.getenv("DB_PORT", 5432)),
    "database": os.getenv("DB_NAME"),
    "ssl_context": ssl_context  # Add SSL context for Neon
}

# Remove any None values that might cause issues
DB_CONFIG = {k: v for k, v in DB_CONFIG.items() if v is not None}

CSV_DIR = os.getenv("CSV_DIR")

print("\n🔌 Attempting to connect to database...")

# === Connect to Neon PostgreSQL via pg8000 ===
try:
    conn = pg8000.connect(**DB_CONFIG)
    print("✅ Successfully connected to database!")
except Exception as e:
    print(f"❌ Connection failed: {e}")
    print("\n💡 Troubleshooting tips:")
    print("   1. Verify your database credentials in GitHub Secrets")
    print("   2. Ensure credentials don't have extra spaces/newlines")
    print("   3. Check if the Neon database is active (not suspended)")
    print("   4. Verify the user has CONNECT privileges")
    raise

cur = conn.cursor()

# === Helpers ===
def is_intermediate_table(filename):
    base = os.path.splitext(filename)[0]
    return base.isupper()

def truncate_table(cursor, table_name):
    try:
        cursor.execute(f"TRUNCATE TABLE {table_name} RESTART IDENTITY CASCADE;")
        print(f"🗑️ Table {table_name} emptied.")
    except Exception as e:
        print(f"❌ Error truncating {table_name}: {e}")

# === Main import loop ===
for file in sorted(os.listdir(CSV_DIR)):
    if not file.endswith(".csv"):
        continue

    table_name = os.path.splitext(file)[0]
    csv_path = os.path.join(CSV_DIR, file)

    # Truncate table first
    truncate_table(cur, table_name)

    print(f"\n📥 Importing {file} → table {table_name}...")

    # Read CSV
    df = pd.read_csv(csv_path, sep=";", quotechar='"', escapechar="'")

    # Drop _id for intermediate tables
    if is_intermediate_table(file) and "_id" in df.columns:
        df = df.drop(columns=["_id"])
        print(f"   ↳ Dropped '_id' (auto-generated by SERIAL).")

    # Convert Ja/Nee to boolean, except for HAS_PROPERTY
    for col in df.columns:
        if col == "HAS_PROPERTY":
            continue
        if df[col].astype(str).str.lower().isin(["ja", "nee"]).any():
            df[col] = df[col].map(
                lambda x: True if str(x).lower() == "ja" else (False if str(x).lower() == "nee" else None)
            )
            print(f"   ↳ Converted 'Ja'/'Nee' to boolean in column '{col}'.")

    # Prepare COPY command
    columns = ','.join(df.columns)
    copy_sql = f"""
        COPY {table_name} ({columns})
        FROM STDIN WITH (FORMAT CSV, DELIMITER ';', QUOTE '"', ESCAPE '''', HEADER TRUE);
    """

    # Write temporary CSV for proper encoding
    tmp_path = os.path.join(CSV_DIR, "_temp.csv")
    df.to_csv(tmp_path, index=False, sep=";", quotechar='"', escapechar="'")

    # Import into PostgreSQL
    with open(tmp_path, "r", encoding="utf-8") as f:
        try:
            cur.copy_expert(copy_sql, f)
            conn.commit()  # Commit after each import
            print(f"✅ Imported {len(df)} rows into {table_name}.")
        except Exception as e:
            print(f"❌ Error importing {table_name}: {e}")
            conn.rollback()  # Rollback on error

    os.remove(tmp_path)

# === Close connection ===
cur.close()
conn.close()
print("\n🎉 All CSVs processed successfully!")