import os
import psycopg2
import pandas as pd
from dotenv import load_dotenv
import pg8000.native

# === Load environment variables from .env ===
load_dotenv()

DB_CONFIG = {
    "user": os.getenv("DB_USER"),
    "password": os.getenv("DB_PASSWORD"),
    "host": os.getenv("DB_HOST"),
    "port": int(os.getenv("DB_PORT", 5432)),
    "database": os.getenv("DB_NAME"),
    "ssl": True  # Required for Neon
}

conn = pg8000.native.Connection(**DB_CONFIG)
cur = conn.cursor()

CSV_DIR = os.getenv("CSV_DIR")

# === Connect to PostgreSQL ===
conn = psycopg2.connect(**DB_CONFIG)
conn.autocommit = True
cur = conn.cursor()

# === Helpers ===
def is_intermediate_table(filename):
    base = os.path.splitext(filename)[0]
    return base.isupper()

def truncate_table(cursor, table_name):
    try:
        cursor.execute(f"TRUNCATE TABLE {table_name} RESTART IDENTITY CASCADE;")
        print(f"🗑️ Table {table_name} emptied.")
    except Exception as e:
        print(f"❌ Error truncating {table_name}: {e}")

# === Main import loop ===
for file in os.listdir(CSV_DIR):
    if not file.endswith(".csv"):
        continue

    table_name = os.path.splitext(file)[0]
    csv_path = os.path.join(CSV_DIR, file)

    # Truncate table first
    truncate_table(cur, table_name)

    print(f"\n📥 Importing {file} → table {table_name}...")

    # Read CSV
    df = pd.read_csv(csv_path, sep=";", quotechar='"', escapechar="'")

    # Drop _id for intermediate tables
    if is_intermediate_table(file) and "_id" in df.columns:
        df = df.drop(columns=["_id"])
        print(f"   ↳ Dropped '_id' (auto-generated by SERIAL).")

    # Convert Ja/Nee to boolean, except for HAS_PROPERTY
    for col in df.columns:
        if col == "HAS_PROPERTY":
            continue  # skip this column
        if df[col].astype(str).str.lower().isin(["ja", "nee"]).any():
            df[col] = df[col].map(
                lambda x: True if str(x).lower() == "ja" else (False if str(x).lower() == "nee" else None)
            )
            print(f"   ↳ Converted 'Ja'/'Nee' to boolean in column '{col}'.")


    # Prepare COPY command
    columns = ','.join(df.columns)
    copy_sql = f"""
        COPY {table_name} ({columns})
        FROM STDIN WITH (FORMAT CSV, DELIMITER ';', QUOTE '"', ESCAPE '''', HEADER TRUE);
    """

    # Write temporary CSV for proper encoding
    tmp_path = os.path.join(CSV_DIR, "_temp.csv")
    df.to_csv(tmp_path, index=False, sep=";", quotechar='"', escapechar="'")

    # Import into PostgreSQL
    with open(tmp_path, "r", encoding="utf-8") as f:
        try:
            cur.copy_expert(copy_sql, f)
            print(f"✅ Imported {len(df)} rows into {table_name}.")
        except Exception as e:
            print(f"❌ Error importing {table_name}: {e}")

    os.remove(tmp_path)

# === Close connection ===
cur.close()
conn.close()
print("\n🎉 All CSVs processed successfully!")
